---
title: "data_project"
output: pdf_document
date: "2024-03-20"
---

# Final Project

```{r, include = TRUE, warning = FALSE, message = FALSE}
library(tidyverse)
library(modelr)
library(sf)

# Load data
df <- read_csv("lyde.csv") #lanternfly data
road_sf <- read_sf("tl_2019_us_primaryroads.shp") #major US roads data

```

# Map
```{r fig.height=10, fig.width=12}
library(maps)
# library(maptools)
usa <- map_data("usa")
df %>%
  filter(latitude>25 & latitude <50 & longitude > -130) #Filter to continental US

# lonlat_to_county_sp <- function(pointsDF) {
#     # Prepare SpatialPolygons object with one SpatialPolygon
#     # per state (plus DC, minus HI & AK)
#     states <- map('county', fill=TRUE, col="transparent", plot=FALSE)
#     IDs <- sapply(strsplit(states$names, ":"), function(x) x[1])
#     states_sp <- map2SpatialPolygons(states, IDs=IDs,
#                      proj4string=CRS("+proj=longlat +datum=WGS84"))
# 
#     # Convert pointsDF to a SpatialPoints object 
#     pointsSP <- SpatialPoints(pointsDF, 
#                     proj4string=CRS("+proj=longlat +datum=WGS84"))
# 
#     # Use 'over' to get _indices_ of the Polygons object containing each point 
#         indices <- over(pointsSP, states_sp)
# 
#     # Return the state names of the Polygons object containing each point
#     stateNames <- sapply(states_sp@polygons, function(x) x@ID)
#     stateNames[indices]
# }
# 
# pointsDF <- df[, c("latitude", "longitude")]
# 
# df <- df %>%
#   mutate(county_info = lonlat_to_county_sp(pointsDF))

# # plot the US
# ggplot() +
#   geom_polygon(data=usa, aes(long, lat, group = group), fill = "white", colour = "black") + #plot blank US map
#   geom_point(data = df, aes(x = longitude, y = latitude), size = .5, color = "blue", alpha = .2) + #Plots lanternfly spottings
#   geom_sf(data = road_sf) + #plot major roads
#   scale_y_continuous(limits = c(25, 50)) +
#   scale_x_continuous(limits = c(-125, -65))
# 
# # plot the northeast
# ggplot() +
#   geom_polygon(data=usa, aes(long, lat, group = group), fill = "white", colour = "black") + #plot blank US map
#   geom_point(data = df, aes(x = longitude, y = latitude, color = factor(year)), size = .5, alpha = .2) + #Plots lanternfly spottings
#   geom_sf(data = road_sf) + #plot major roads
#   scale_y_continuous(limits = c(35, 44)) +
#   scale_x_continuous(limits = c(-85, -70))+
#   guides(color = guide_legend(override.aes = list(size = 3))) +
#   theme(legend.key.size = unit(1.5, "lines"))


ggplot() +
  geom_polygon(data=usa, aes(long, lat, group = group), fill = "white", colour = "black") + #plot blank US map
  geom_point(data = df, aes(x = longitude, y = latitude, color = factor(year)), size = .5, alpha = .2) + #Plots lanternfly spottings
  geom_sf(data = road_sf) + #plot major roads geom_point(data = df, aes(x = longitude, y = latitude))
  facet_wrap(~ year, nrow = 2) +
  scale_y_continuous(limits = c(35, 44)) +
  scale_x_continuous(limits = c(-85, -70))+
  guides(color = guide_legend(override.aes = list(size = 3))) +
  theme(legend.key.size = unit(1.5, "lines"))

```

# Model 1
```{r, warning = FALSE, message = FALSE, fig.width = 10, fig.height = 3}

df %>% filter(!is.na(state))
model_1 <- lm(state~year, data = df)

```